"""ScrapAI Python Library.

This package provides a programmatic interface to ScrapAI.

Example:
    from scrapai import setup, list_spiders, crawl, show_items

    setup()
    spiders = list_spiders(project="news")
    result = crawl(spider="bbc_co_uk", project="news", limit=10)
    items = show_items(spider="bbc_co_uk", project="news", limit=5)
"""

from scrapai.api import (
    setup,
    verify,
    list_projects,
    list_spiders,
    get_spider,
    import_spider,
    export_spider,
    delete_spider,
    generate_spider,
    repair_spider,
    crawl,
    crawl_all,
    show_items,
    export_items,
    health_check,
    health_check_spider,
    queue_add,
    queue_bulk,
    queue_list,
    queue_process,
    db_stats,
    db_query,
    inspect_url,
    SpiderInfo,
    GenerateSpiderResult,
    CrawlResult,
    ItemsResult,
    ExportResult,
    HealthReport,
    SpiderHealthResult,
    QueueItem,
    BatchResult,
    FailedQueueItem,
    DbStats,
    SetupResult,
    VerifyResult,
    ProjectInfo,
    InspectionResult,
    SpiderNotFoundError,
    ProjectNotFoundError,
    GenerationFailedError,
    LLMNotConfiguredError,
    CrawlError,
    ExportError,
    QueryNotAllowedError,
    ValidationError,
    ScrapAIConfigError,
)

__version__ = "0.1.0"

__all__ = [
    "setup",
    "verify",
    "list_projects",
    "list_spiders",
    "get_spider",
    "import_spider",
    "export_spider",
    "delete_spider",
    "generate_spider",
    "repair_spider",
    "crawl",
    "crawl_all",
    "show_items",
    "export_items",
    "health_check",
    "health_check_spider",
    "queue_add",
    "queue_bulk",
    "queue_list",
    "queue_process",
    "db_stats",
    "db_query",
    "inspect_url",
    "SpiderInfo",
    "GenerateSpiderResult",
    "CrawlResult",
    "ItemsResult",
    "ExportResult",
    "HealthReport",
    "SpiderHealthResult",
    "QueueItem",
    "BatchResult",
    "FailedQueueItem",
    "DbStats",
    "SetupResult",
    "VerifyResult",
    "ProjectInfo",
    "InspectionResult",
    "SpiderNotFoundError",
    "ProjectNotFoundError",
    "GenerationFailedError",
    "LLMNotConfiguredError",
    "CrawlError",
    "ExportError",
    "QueryNotAllowedError",
    "ValidationError",
    "ScrapAIConfigError",
]
